package com.codesprint.model;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.LocalDate;

/**
 * Task entity class representing a task in the database.
 * Uses JPA for ORM and Lombok for reducing boilerplate code.
 */
@Entity
@Table(name = "tasks")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Task {

    /**
     * Unique identifier for the task.
     * Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Title of the task.
     */
    private String title;

    /**
     * Detailed description of the task.
     */
    private String description;

    /**
     * Status of the task (e.g., PENDING, COMPLETED, IN_PROGRESS).
     */
    private String status;

    /**
     * Date when the task was created.
     */
    private LocalDate createdDate;

    /**
     * Constructor for creating a task without ID (for new tasks).
     * 
     * @param title the title of the task
     * @param description the description of the task
     * @param status the status of the task
     * @param createdDate the creation date of the task
     */
    public Task(String title, String description, String status, LocalDate createdDate) {
        this.title = title;
        this.description = description;
        this.status = status;
        this.createdDate = createdDate;
    }

}
